[package]
name = "runar-nips"
version = "0.0.0"
edition = "2021"

[dependencies]
regex = { version = "1.10.2", default-features = false }
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
